### ISSUE TITLE
Rename from `nuxt-speedkit` to `nuxt-booster`

### ISSUE THREAD

**Issue by ThornWalli** [basics/nuxt-booster#921]
# Todos

- [ ] Feature must be completed first.
  - https://github.com/GrabarzUndPartner/nuxt-speedkit/pull/851
- [x] Rename
  - [x] Documentaion
  - [x] Runtime Alias
  - [x] Components
  - [x] Composables
- [x] `package.json`
  - [x] `nuxt-speedkit` to `nuxt-booster`
- [ ] Rename Github repository
  - [ ] Redirect?
- [ ] Rename NPM Package
  - [ ] Old versions should remain available with old names `nuxt-speedkit`.
  - [ ] Redirect?
- [ ] Domain?

**Github**
- https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**NPM**
- https://docs.npmjs.com/cli/v10/commands/npm-deprecate
- https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

### Documentaion

Only `v3`.

### Runtime Alias

Renamed Alias from `#speedkit` to `#booster`.

e.g. `#booster/hydrate`

### Components

| Old               | New              |
| ----------------- | ---------------- |
| `SpeedkitPicture` | `BoosterPicture` |
| `SpeedkitImage`   | `BoosterImage`   |
| `SpeedkitLayer`   | `BoosterLayer`   |
| `SpeedkitIframe`  | `BoosterIframe`  |
| `SpeedkitYoutube` | `BoosterYoutube` |
| `SpeedkitVimeo`   | `BoosterVimeo`  |

### Composables

| Old                    | New                           |
| ---------------------- | ----------------------------- |
| `useFonts`             | `useBoosterFonts`             |
| `useCritical`          | `useBoosterCritical`          |
| `useConfig`            | `useBoosterConfig`            |
| `useComponentObserver` | `useBoosterComponentObserver` |

> Composables are only announced globally (e.g. `#imports`) with the renaming.
